version: '3.8'

services:
  gastrosyncbackend.presentation:
    container_name: gastrosyncbackend-presentation-gastrosyncbackend
    image: ${DOCKER_REGISTRY-}gastrosyncbackendpresentation
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    build:
      context: .
      dockerfile: GastroSyncBackend.Presentation/Dockerfile
    ports:
        - "8080:80"
        - "8443:443"
    networks:
      - gastrosync_elk_network
    depends_on:
      elasticsearch:
          condition: service_healthy
      kibana:
          condition: service_healthy
      sqlserver:
        condition: service_healthy
        
  elasticsearch:
    container_name: elasticsearch-gastrosyncbackend
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - gastrosync_elk_network
    healthcheck:
      test: ["CMD-SHELL", "curl -sSL http://localhost:9200/_cluster/health?pretty || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3

  kibana:
    container_name: kibana-gastrosyncbackend
    image: docker.elastic.co/kibana/kibana:7.15.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 5601:5601
    volumes:
      - kbdata:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks:
      - gastrosync_elk_network
    healthcheck:
      test: ["CMD-SHELL", "curl -sSL http://localhost:5601 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3

  sqlserver:
    container_name: sqlserver-gastrosyncbackend
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    ports:
      - 1433:1433
    networks:
      - gastrosync_elk_network
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPass@word
      - MSSQL_PID=Express
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "MyPass@word", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  esdata:
    driver: local
  kbdata:
    driver: local
  sqldata:
    driver: local

networks:
  gastrosync_elk_network:
