name: Deploy to ECR

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4.1.1
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2.0.1
    
    - name: Build, tag, and push images to Amazon ECR
      env:
        ECR_REGISTRY: public.ecr.aws/o3f5f0c7
        IMAGE_TAG: latest
      run: |
        docker-compose build
        docker images --format '{{.Repository}}:{{.Tag}}' | grep -E 'gastrosyncbackendpresentation|elasticsearch-gastrosyncbackend|kibana-gastrosyncbackend|sqlserver-gastrosyncbackend' | xargs -I {} docker tag {} $ECR_REGISTRY/{}:$IMAGE_TAG
        docker images --format '{{.Repository}}' | grep -E 'gastrosyncbackendpresentation|elasticsearch-gastrosyncbackend|kibana-gastrosyncbackend|sqlserver-gastrosyncbackend' | xargs -I {} docker push $ECR_REGISTRY/{}:$IMAGE_TAG
    - name: Set output
      id: some_step
      run: |
        echo "NAME=value" >> $GITHUB_ENV
