name: Deploy to AWS
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to AWS EC2
      uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.8
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_default_region: sa-east-1  
        dot_env: ${{ secrets.DOT_ENV }}  
